language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1

    # The SDK version used to compile your project
    - android-24
    
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

script: ./gradlew assembleDebug
